name: Compressor

on: [push]

env:
  FILE_URL: https://master.dl.sourceforge.net/project/sgsi137/Test/system.img
  FILE_NAME:
  TZ: Asia/Kolkata
jobs:
  Compress:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt update; sudo apt install aria2 git unace p7zip-full p7zip-rar sharutils uudeview mpack arj aptitude liblzma-dev liblz4-tool gawk aria2 brotli lz4 img2simg -y

       - name: Download File
         run: |
              mkdir -p file
              cd file
              if [ -z "$FILE_URL" ]; then
              echo "Enter url of file to download"
              exit 1;
              else echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c -c -m 0 $FILE_URL;
              fi
              sudo img2simg system.img sys.img

       - name: Decompress File
         run: |
              cd file
              git clone https://github.com/xpirt/img2sdat sdat ; mv sys.img sdat
              cd sdat ; sudo chmod -R 777 .; sudo ./img2sdat.py -o tmp -v 4 -p system sys.img
       
       - name: Compress File
         run: |
              cd file/sdat/tmp
              ls
              echo "Compressing your file. wait... it can take some minutes"
              brotli -9jft *.new.dat
              ls

       - name: Upload File
         run: |
              cd file/sdat/tmp
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd /home/pfs/project/sgsi137/Test/Cos\r\"
              set timeout -1
              send \"put *\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
