name: Compressor

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/alpha.zip
  FILE_NAME:
  TZ: Asia/Kolkata
jobs:
  Compress:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt install expect aria2 -y

       - name: Download File
         run: |
              mkdir -p file
              cd file
              if [ -z "$FILE_URL" ]; then
              echo "Enter url of file to download"
              exit 1;
              else echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c -c -m 0 $FILE_URL;
              fi

       - name: Decompress File
         run: |
              cd file
              ls
              mkdir -p final
              if [ -f *.zip ]; then
              echo "Decompressing your file. wait... it will take some seconds"
              unzip -q *.zip -d ./final;
              else echo "File is not a zip!"
              exit 1;
              fi
              cd final
              ls
       
       - name: Compress File
         run: |
              cd file/final
              ls
              echo "Compressing your file. wait... it can take some minutes"
              if [ -z "$FILE_NAME" ]; 
              then xz -fev9 *; 
              else xz -cfev9 * > $FILE_NAME.xz ; 
              fi
              ls

       - name: Upload File
         run: |
              cd file/final
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
