name: Compressor

on: [push]

env:
  FILE_URL: https://master.dl.sourceforge.net/project/gsis137/compressed/system/system.new.dat?viasf=1
  FILE_NAME:
  TZ: Asia/Kolkata
jobs:
  Compress:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt update; sudo apt install aria2 git unace p7zip-full p7zip-rar sharutils uudeview mpack arj aptitude liblzma-dev liblz4-tool gawk aria2 brotli lz4 img2simg -y

       - name: Download File
         run: |
              mkdir -p file
              cd file
              if [ -z "$FILE_URL" ]; then
              echo "Enter url of file to download"
              exit 1;
              else echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c -x16 -m 0 $FILE_URL;
              fi
       
       - name: Compress File
         run: |
              cd file
              ls -lh *
              echo "Compressing your file. wait... it can take some minutes"
              sudo brotli -7jf *.dat
              ls

       - name: Upload File
         run: |
              cd file
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}/system\r\"
              set timeout -1
              send \"put *.br\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
