name: Compressor

on: [push]

env:
  URL: https://master.dl.sourceforge.net/project/sgsi137/Test/Cos/Firmware_tree.txt?viasf=1
  URL2: https://master.dl.sourceforge.net/project/sgsi137/Test/Cos/cos_firmware.img?viasf=1
  URL3: https://master.dl.sourceforge.net/project/sgsi137/Test/Cos/cos_stock.img?viasf=1
  URL4: https://master.dl.sourceforge.net/project/sgsi137/Test/cos_1.img?viasf=1
  URL5: https://master.dl.sourceforge.net/project/sgsi137/Test/build.zip?viasf=1
jobs:
  Compress:
    runs-on: ubuntu-latest 

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt install expect aria2 -y

       - name: Download File
         run: |
              mkdir -p file
              cd file
              if [ -z "$URL" ]; then
              echo "Enter url of file to download"
              exit 1;
              else echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c -x16 $URL; aria2c -x16 $URL2; aria2c -x16 $URL3; aria2c -x16 $URL4; aria2c -x16 $URL5
              fi

       - name: Upload File
         run: |
              cd file
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
